### ISSUE TITLE
xHotfix - $LASTEXITCODE' cannot be retrieved

### ISSUE THREAD

**Issue by Zuldan** [PowerShell/xWindowsUpdate#10]
The error below is generated when trying to install a Hotfix. The issue can be re-produced by trying to install one of the following hotfixes; 

KB2996883
KB3046481
KB3054249

-------------------------- Error ----------------------

4252 Error            MIResult: 1Error Message: The variable '$LASTEXITCODE' cannot be retrieved
                                            because it has not been set.Message ID: VariableIsUndefinedError Category:
                                            7Error Code: 7Error Type: MI
--------------------------- Error ----------------------

It may be related to the hotfix not installing due a pending reboot as the hotfixes do eventually install. 
If it is pending reboot related, the xHotfix resource should be checking for pending reboots and NOT trying install a hotfix if a pending reboot exists (sending a warning) OR don't check for $LASTEXITCODE if a pending reboot exists. 

FYI, we prefer not to use xPendingReboot on production server as we can't risk production servers going into an endless reboot if there is some issue. A warning message from xHotfix about a pending reboot is a much safer option.

**Comment by mprahl** [comment]
@Zuldan Pull request #11 should fix your issue. I basically added a check to make sure $LASTEXITCODE existed prior to evaluating it. It's in the dev branch now, but I'm hoping it'll be released in the near future.

**Comment by Zuldan** [comment]
Fantastic PrahIM93. Thank you so much! Let's hope it gets to Master soon. I'm going to start testing the dev version.

**Comment by mprahl** [comment]
Cool @Zuldan! Let me know how it works for you. I've been developing DSC configurations with that dev version for a while now and it's been working well for me.

**Comment by Zuldan** [comment]
PrahIM9 it's been working fine for me. Thanks again. I'll close this issue when it's your fix is pushed to master.

**Comment by mprahl** [comment]
@Zuldan, the resource has been updated to 2.3.0.0. Please give it a try and see how it works.
