### ISSUE TITLE
xWindowsUpdate: Documentation incorrectly specifies resource is called xHotfix.

### ISSUE THREAD

**Issue by ChrisLGardner** [PowerShell/xWindowsUpdate#58]
Documentation in Readme and examples use xHotfix but resource in code is called xWindowsUpdate, one or the other should be changed so it's actually correct. Which one is the preferred naming?

**Comment by johlju** [comment]
The resource xWindowsUpdate has the friendly name xHotFix in the schema.mof. The README.md is being worked on in PR #62.

**Comment by johlju** [comment]
This was resolved in PR #72.
