### ISSUE TITLE
Access Denied error during Push Windows Update

### ISSUE THREAD

**Issue by kiransqldba** [PowerShell/xWindowsUpdate#68]
Hello,

I am trying below config file to push windows udpate and getting access denied error.
Anyone has idea about what's wrong with this?
```
Configuration Update_test_config
{
    param(
            

        [Parameter(Mandatory = $true)]
        [ValidateNotNullorEmpty()]
        [System.Management.Automation.PSCredential]
        [System.Management.Automation.Credential()]
        $MyCredential

    )
    
    Import-DscResource -Module xWindowsUpdate

    Node $Node1
    {
        xMicrosoftUpdate "EnableMSUpdate"
        {
            Ensure = "Present"
        }
    }
}

$cd = @{
    AllNodes = @(
        @{
            NodeName             = 'WSFC1'
            PSDscAllowDomainUser = $true
            PSDscAllowPlainTextPassword = $true

        }
    )
}

$crendentials = Get-Credential -Message "Enter credentials"
Update_test_config -MyCredential @credentials


$Node1 = "WSFC1"
Update_test_config -OutputPath E:\Automation\DSC_Scripts\Learning_Script

Start-DscConfiguration -Path C:\Windows\system32\Update_test_config -ComputerName WSFC1 -Verbose -Wait
```
Error Details :
```
Access is denied.

CategoryInfo : PermissionDenied: (root/Microsoft/...gurationManager:String) [], CimException
FullyQualifiedErrorId : HRESULT 0x80070005
PSComputerName : WSFC1
```

**Comment by kiransqldba** [comment]
I added VM box to trusted group using below command

 winrm set winrm/config/client '@{TrustedHosts="WSFC1"}'

but still getting below error
Access is denied.
    + CategoryInfo          : PermissionDenied: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : HRESULT 0x80070005
    + PSComputerName        : WSFC1

Does anyone knows how to connect to remote server using credentials?

**Comment by johlju** [comment]
Can you provide the verbose logs so we can see how far it comes before it says access denied? Obfuscate any sensitive information.

**Comment by johlju** [comment]
Closing this because of lack of response. Assume this issue has been resolved by other means.
