### ISSUE TITLE
Feature Request:  Set Automatic Windows Update

### ISSUE THREAD

**Issue by jbenson444** [PowerShell/xWindowsUpdate#7]
I am not sure if this the right place to put this, because it's not really an "issue" as much as a feature request.  I had been testing this using Server 2012R2 and Server 2016 Preview 3 core, and it wasn't updating what the GUI shows as far as Microsoft update being set to Automatic or Manual.  Then I read on here that all it is supposed to do is check the box in the GUI for enabling Microsoft Update.

In Server Core versions I would like to be able to set the Windows Update Settings to Automatic or Manual and have that change reflected in the GUI.  I poked around on MSDN looking at the Microsoft.Update.ServiceManager stuff and that's well above my head.

Also, the documentation should be updated to mention that this enables Microsoft Update, and not Windows Update, which are two separate things.

**Comment by TravisEz13** [comment]
I believe this feature was added in xWindowsUpdateAgent

**Comment by johlju** [comment]
Closing this issue as per previous comment. If this issue was closed in error, then please reopen or comment.
