### ISSUE TITLE
Clarification needed if xWindowsUpdateAgent makes changes to registry

### ISSUE THREAD

**Issue by ewhitesides** [PowerShell/xWindowsUpdate#76]
When Notifications parameter is set to ScheduledInstallation/Disabled, does it modify the registry settings?

ie registry areas like:
"HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate\AU"

Or are these settings only set during the instance of windows update that is run when the configuration is being applied.

**Comment by johlju** [comment]
Seems it should set this if it is not in desired state

https://github.com/PowerShell/xWindowsUpdate/blob/1afc7a4a45c7eea5e46a01e562860b050b58aa27/DscResources/MSFT_xWindowsUpdateAgent/MSFT_xWindowsUpdateAgent.psm1#L484-L497

**Comment by ewhitesides** [comment]
I think it might be calling an instance of the windows update object....the code block you quoted eventually drills down to a function 'Get-WuaAu'?

So it seems that it is not making permanent changes to the registry.

**Comment by johlju** [comment]
Seems it is `Get-WuaAuSettings` and which returns an object that are changed and then saved. When it saves it does not write to registry? 

https://github.com/PowerShell/xWindowsUpdate/blob/b10c090e8523a8129757b5a3a00ffbdd40dce813/DscResources/MSFT_xWindowsUpdateAgent/MSFT_xWindowsUpdateAgent.psm1#L209-L221
