### ISSUE TITLE
sporadic DSC error

### ISSUE THREAD

**Issue by ewhitesides** [PowerShell/xWindowsUpdate#79]
I am constantly getting errors in the DSC Operational Log, when I check the system in verbose mode I get the following in my DSC failure

VERBOSE: []: LCM:  [ Start  Test     ]  [[xWindowsUpdateAgent]WUSetting1]
VERBOSE: []:                            [[xWindowsUpdateAgent]WUSetting1] TryGet RebootRequired...
VERBOSE: []:                            [[xWindowsUpdateAgent]WUSetting1] Got rebootRequired: False
VERBOSE: []:                            [[xWindowsUpdateAgent]WUSetting1] Searching for updating using: IsHidden=0 and IsInstalled=0
VERBOSE: []:                            [[xWindowsUpdateAgent]WUSetting1] Get default search service: 7971f918-a847-4430-9279-4a52d1efe18d
VERBOSE: []:                            [[xWindowsUpdateAgent]WUSetting1] updateNow compliant: False
VERBOSE: []:                            [[xWindowsUpdateAgent]WUSetting1] notifications compliant: True
VERBOSE: []:                            [[xWindowsUpdateAgent]WUSetting1] service compliant: True
VERBOSE: []: LCM:  [ End    Test     ]  [[xWindowsUpdateAgent]WUSetting1] False in 3.9310 seconds.
VERBOSE: []: LCM:  [ End    Resource ]  [[xWindowsUpdateAgent]WUSetting1]

my settings are:

xWindowsUpdateAgent WUSetting1 {
            IsSingleInstance = 'Yes'
            UpdateNow        = $true
            Category         = @('Security','Important','Optional')
            Source           = 'MicrosoftUpdate'
        }

my LCM is

ActionAfterReboot              : ContinueConfiguration
AgentId                        : C69D62DD-D5F5-11E7-9F55-00155DF2B712
AllowModuleOverWrite           : False
CertificateID                  :
ConfigurationDownloadManagers  : {}
ConfigurationID                :
ConfigurationMode              : ApplyAndMonitor
ConfigurationModeFrequencyMins : 60
Credential                     :
DebugMode                      : {NONE}
DownloadManagerCustomData      :
DownloadManagerName            :
LCMCompatibleVersions          : {1.0, 2.0}
LCMState                       : Idle
LCMStateDetail                 :
LCMVersion                     : 2.0
StatusRetentionTimeInDays      : 10
SignatureValidationPolicy      : NONE
SignatureValidations           : {}
MaximumDownloadSizeMB          : 500
PartialConfigurations          :
RebootNodeIfNeeded             : True
RefreshFrequencyMins           : 60
RefreshMode                    : Push
ReportManagers                 : {}
ResourceModuleManagers         : {}

**Comment by johlju** [comment]
Thanks for the configuration information and the verbose log. I'm not seeing any errors in the verbose log. What error are you getting? Is there something that should happen but does not happen?

**Comment by ewhitesides** [comment]
the verbose log shows this:
VERBOSE: []: [[xWindowsUpdateAgent]WUSetting1] updateNow compliant: **False**

which results in the entire config reporting as false, which then sends an alert to me that the computer is out of compliance.

my understanding of this module is that it does a one time update at the time a configuration is pushed.  so the rest of the time when the LCM is in monitor mode, it should not report an error?

**Comment by johlju** [comment]
It returns false when this is not true.

https://github.com/PowerShell/xWindowsUpdate/blob/b10426e212827ab7a182b6b45f31fb46c9dfa6ae/DscResources/MSFT_xWindowsUpdateAgent/MSFT_xWindowsUpdateAgent.psm1#L548-L549

And `$Get.UpdateNow` is set to `$false` if `$totalUpdatesNotInstalled` is 1 or more, or if reboot is required.

https://github.com/PowerShell/xWindowsUpdate/blob/b10426e212827ab7a182b6b45f31fb46c9dfa6ae/DscResources/MSFT_xWindowsUpdateAgent/MSFT_xWindowsUpdateAgent.psm1#L370-L374

**Comment by johlju** [comment]
Are you getting an notification when there is a need for a reboot?

**Comment by ewhitesides** [comment]
my guess is that there is a pending update.

on an almost daily basis, there's an update for MS Defender.  So I set the registry setting for AutoInstall Minor updates to take care of that on its own, but that doesn't always sync up with when DSC does a check.
 ("HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate\AU\AutoInstallMinorUpdates")

I configured a logging tool to look into the DSC Operational logs, and if there are any errors (logs report category as error when a config returns false), to send me a notification.

so perhaps the confusion is with the wording 'updatenow'.... it seems it's bundling two different concepts.  one concept is that there is a pending reboot , the other is that there is a pending update waiting.

**Comment by johlju** [comment]
Do you have a suggestion on how to improve this?

**Comment by ewhitesides** [comment]
yeah i do, i'll think through it for a bit and let you know.

**Comment by ewhitesides** [comment]
this is just an idea on an external parameter for the user to make use of, and it depends on if DSC has some way of detecting if is a manual push vs a routine internal check:

'updateWhen' = 'atPushOnly'
updateNow will report $true all the time unless it is a manual push.  if manual push, will check and report as it does (pending reboots/pending updates) and base $true/$false response on that outcome.

'updateWhen = 'All'
updateNow will work as it does now, reporting $false if pending reboots/pending updates at all times

### the following would be extra credit :), but also too many options may cause confusion

'SubCategory' = 'MajorUpdatesOnly'
updateNow return $false when there is a pending update that is NOT included in what "HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate\AU\AutoInstallMinorUpdates" searches for

"SubCategory' = 'All'
updateNow will work as it does now, reporting $false if pending reboots/pending updates at all times

'updateWhen' works at 1 step lower than updateNow, and 'SubCategory' works at 2 steps underneath updateNow.  Both contribute to updateNow's final decision to report true or false.

**Comment by johlju** [comment]
As far as I know there is no way of determine if the run is a initial run (for either pull or push) or consistency run (for either pull or push). So not sure `'updateWhen' = 'atPushOnly'` would work?

> ...when there is a pending update that is NOT included in what "HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate\AU\AutoInstallMinorUpdates" searches for

I like the idea. How would we check for that?

**Comment by ewhitesides** [comment]
I think we would need to basically program in the inverse of what AutoInstallMinorUpdates searches for.

So we would need to look at the source code for the windows update binary to see what effect the AutoInstallMinorUpdates is filtering for?  I'm assuming you work for MS.... do you have access?

Otherwise there might be ways of inferring what it is doing by looking at the difference in properties of update packages, but that would be a lot of work reverting back and forth through a VM image.

**Comment by johlju** [comment]
I do not have access to that. Assume that we can only use the information that is publicly available 🙂 For you particular issue, and looking at what you said here

>...which results in the entire config reporting as false, which then sends an alert to me that the computer is out of compliance.

>...so perhaps the confusion is with the wording 'updatenow'.... it seems it's bundling two different concepts. one concept is that there is a pending reboot , the other is that there is a pending update waiting.

If the configuration has `UpdateNow` set to `$true`, then having `UpdateNow` set to `$false` when there is a pending update seems correct. The target node would not have gotten the update unless it needed it?

It the problem is that it reports `$false` when there is a pending reboot, then maybe that is a problem? Maybe it should only report `$false` when there is an update that is waiting to be installed. If there is a pending reboot the resource [xPendingReboot](https://github.com/PowerShell/xPendingReboot) might be able to be used to restart the target node instead. I'm just thinking out loud, there might be a good reason for this resource to report when there is a pending reboot, maybe because it cannot install updates if there is a pending reboot. But maybe the documentation could be updated to reflect that xPendingReboot must be used in conjunction with this resource if that is changed. 🤔
