### ISSUE TITLE
Run xWindowsUpdate only on Initial

### ISSUE THREAD

**Issue by trolleyboy** [PowerShell/xWindowsUpdate#86]
We use DSC via Azure Automation and have it configured to auto-correct any consistency issues.  
It's my understanding that xWindowsUpdateAgent with UpdateNow = $true will run with each consistency check (every 15min in our case) and if updates are available, will install them and reboot the system (if necessary).  
This is great for an Initial consistency check, but I'd prefer to let the Azure Automation Update Management service take over and manage updates after a new VM is up and running. 

Is such an option to only run xWindowsUpdateAgent during the Initial consistency check already available?  If not, can such a feature be added?

**Comment by gaelcolas** [comment]
> Is such an option to only run xWindowsUpdateAgent during the Initial consistency check already available? 

No, I don't think so.

> can such a feature be added?

I'm afraid that doing so would go against the principles of Desired State & eventual convergence that DSC abide to.
Once you set a setting, it must be enforced and no knowledge of first run or second run is (or should be) kept. The resource should enforce idempotency, no matter how many times it is ran.

For this kind of behaviour you are not configuring a Desired State (fully patched all the time), so you'd have to either manage this sequentialisation (do x then do y) outside of DSC (a provisioning Config then a running config), or create your custom resource that would persist a state.

**Comment by trolleyboy** [comment]
OK thanks for the clarification.  Perhaps I'll look at running a script on VM deployment that uses something like PSWindowsUpdate.

**Comment by gaelcolas** [comment]
Yep, or you can Invoke-DscResource if you do that outside from DSC.
